name: tour-project

services:
  minimal-api-dev:
    build: .
    image: minimal-api-dev:latest
    ports:
      - "7272:7272"
    env_file:
      - .env

networks:
  default:
    name: tour_network
    external: true
